import type {ReactNode} from 'react';
import type {FlowOverview} from '../../shared/flow';
import {accountEvents,accountTotals,type PaymentRole} from '../../shared/flow-view';
export function shortAddress(s:string){return s.slice(0,6)+'…'+s.slice(-4);}
export function accountLabel(data:FlowOverview|undefined,address:string){const match=Object.entries(data?.deployment?.accounts||{}).find(([,a])=>a.toLowerCase()===address.toLowerCase());return match?({merchant:'健身房',userA:'会员 A',userB:'会员 B',payout:'经营收款账户',nextPayout:'关联收款账户'} as Record<string,string>)[match[0]]:shortAddress(address);}
function BillList({data,role,onAnalyze}:{data?:FlowOverview;role:PaymentRole;onAnalyze:(eventId:string)=>void}){
  const d=data?.deployment,events=accountEvents(data?.events||[],d,role);
  return <section className="card bill-card" data-testid="account-bills"><div className="section-title"><h2>{role==='merchant'?'收支账单':'我的账单'}</h2><span className="subtle">{events.length} 笔</span></div>
    {!events.length?<div className="empty">{role==='merchant'?'还没有收支记录。收到会员付款后，账单会自动出现。':'还没有付款记录。完成一笔付款后，就能在这里查看。'}</div>:<div className="bill-list">{events.map(e=>{
      const incoming=e.to.toLowerCase()===d!.accounts[role].toLowerCase(),other=incoming?e.from:e.to;
      const j=data?.jobs.find(j=>j.eventId===e.id&&j.status!=='stale'),r=data?.reports.find(r=>r.id===j?.reportId);
      const note=r?.status==='complete'&&(r.risk==='attention'||r.risk==='disputed')?'资金变动需核实':undefined;
      return <article className="bill" key={e.id} data-event-id={e.id}><div className={'bill-icon '+(incoming?'incoming':'outgoing')}>{incoming?'↙':'↗'}</div><div className="bill-description"><strong>{role==='merchant'?(incoming?'会员收款':'资金转出'):(incoming?'收到转账':'健身付款')}</strong><p>{accountLabel(data,other)} · {new Date(e.timestamp*1000).toLocaleString('zh-CN')}</p><span className="confirmed">已确认</span>{note&&<span className="bill-note">{note}</span>}</div><div className="bill-value"><strong>{incoming?'+':'−'}{e.amount} <small>GYM</small></strong><button className="link" onClick={()=>onAnalyze(e.id)}>查看分析</button></div></article>;
    })}</div>}{data?.events.length===100&&<p className="subtle">仅显示最近已同步的 100 笔记录中的相关账单，不代表全部历史。</p>}</section>;
}
export function ConsumerScreen({data,role,form,onAnalyze}:{data?:FlowOverview;role:'userA'|'userB';form:ReactNode;onAnalyze:(eventId:string)=>void}){return <div data-testid="consumer-screen"><div className="page-heading"><div><span className="eyebrow">会员账户</span><h1>今天，练一下。</h1><p>付款给健身房，查看自己的余额和账单。</p></div></div><div className="business-grid"><section className="card payment-card"><div className="balance-label">我的余额</div><div className="balance">{data?.ready?data.balances?.[role]||'0':'—'} <span>GYM</span></div><div className="form-divider"/><h2>付给健身房</h2>{form}</section><BillList data={data} role={role} onAnalyze={onAnalyze}/></div></div>;}
export function MerchantScreen({data,form,onAnalyze}:{data?:FlowOverview;form:ReactNode;onAnalyze:(eventId:string)=>void}){const d=data?.deployment,totals=accountTotals(accountEvents(data?.events||[],d,'merchant'),d?.accounts.merchant||'');return <div data-testid="merchant-screen"><div className="page-heading"><div><span className="eyebrow">商家账户</span><h1>收款与资金管理</h1><p>会员付款直接到账。需要用款时，自由转出。</p></div></div><div className="business-stats"><section className="card stat"><span>可转出余额</span><strong>{data?.ready?data.balances?.merchant||'0':'—'} <small>GYM</small></strong></section><section className="card stat"><span>当前账单收款</span><strong>{totals.incoming} <small>GYM</small></strong></section><section className="card stat"><span>当前账单转出</span><strong>{totals.outgoing} <small>GYM</small></strong></section></div><div className="business-grid"><section className="card payment-card"><h2>转出资金</h2><p className="subtle">填写金额和接收账户，确认后转出。</p>{form}</section><BillList data={data} role="merchant" onAnalyze={onAnalyze}/></div></div>;}
