import React,{useState,useEffect,useCallback,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserProvider,JsonRpcProvider,Contract,id,isAddress,formatUnits} from 'ethers';
import type {Dataset,ChainEvent,Report,Evidence,Alert} from '../../shared/types.ts';
import {walletError,writeReady,assertIdentity} from './safety.ts';
import {preferredGym,isManagementRoute,memberEvents,fundingStatus,usefulAlerts,usableReport,investigationNotice} from './presentation.ts';
import {Modal} from './Modal.tsx';
import {starterQuestions,investigationQuestion,assistantReply,toolNames,type Role} from './assistant.ts';
import './styles.css';

async function api<T=any>(path:string,body?:unknown):Promise<T>{
  let response:Response;try{response=await fetch('/api'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});}catch{throw new Error('本机服务连接失败或超时，请检查服务后重试。');}
  let result:any;try{result=await response.json();}catch{throw new Error('本机服务未返回有效数据，请检查服务是否运行。');}if(!response.ok)throw new Error(result.error?.message||'请求失败');return result.data;
}
const short=(s?:string)=>s?s.slice(0,6)+'…'+s.slice(-4):'—';
const date=(seconds:number)=>new Date(seconds*1000).toLocaleString('zh-CN');
const origins:Record<string,string>={'local-chain':'本地演示 · 不涉及真实资金','public-testnet':'公开测试网演示','public-mainnet':'真实以太坊历史研究 · 只读','synthetic':'合成测试'};
const names:Record<string,string>={Transfer:'额度转账',Deposited:'充值',ConsumptionRequested:'发出消费申请',ConsumptionConfirmed:'消费已确认',ConsumptionRejected:'消费已拒绝',ConsumptionCancelled:'申请已取消',ConsumptionExpired:'申请已过期',Refunded:'退回余额',Withdrawn:'商家提现',PayoutAddressChanged:'更新收款账户'};
const jobLabels:Record<string,string>={queued:'等待核查',running:'正在核查',complete:'核查完成',partial:'核查未完成',failed:'核查中断'};
type PublicConfig={datasets:Dataset[];tokenAbi:any[];escrowAbi:any[];localRpc:string;localTestWalletEnabled:boolean};
type Overview={dataset:Dataset;checkpoint:any;snapshot:any;events:ChainEvent[];totalEventCount:number;alerts:Alert[];reports:Report[];latestJob?:any;backgroundMonitoring?:boolean;businessSummary?:{todayRevenue:string;pending:ChainEvent[]}};
function metricLabel(key:string,value:string,ds?:Dataset){
  if(/^\d+$/.test(value)&&ds){if(['amount','assets','liabilities','denominator','revenue','userCredit','availableBefore'].includes(key))return key+'：'+formatUnits(value,ds.decimals)+' '+ds.tokenSymbol;
    if(key==='relativeTotalBps')return '相对日均：'+formatUnits(value,4)+' 倍';if(['singleConcentrationBps','recipientConcentrationBps','basisPoints'].includes(key))return key+'：'+formatUnits(value,2)+'%';}return key+'：'+value;
}
function App(){
  const [route,setRoute]=useState(location.pathname==='/'?'/consumer':location.pathname),[cfg,setCfg]=useState<PublicConfig>(),[datasetId,setDatasetId]=useState(''),[overview,setOverview]=useState<Overview>();
  const [role,setRole]=useState<Role>(()=>location.pathname==='/merchant'?'merchant':location.pathname==='/consumer'||location.pathname==='/'?'member':sessionStorage.getItem('gym-role')==='merchant'?'merchant':'member');
  const [chat,setChat]=useState<{jobId:string;question:string;reply?:string;report?:Report}[]>([]),[chatInput,setChatInput]=useState('');
  const lastMember=useRef('');
  const [account,setAccount]=useState(''),[wallet,setWallet]=useState<any>(),[localAccounts,setLocalAccounts]=useState<string[]>([]),[user,setUser]=useState<any>(),[walletChain,setWalletChain]=useState<number>();
  const [dataError,setDataError]=useState(''),[configError,setConfigError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [job,setJob]=useState<any>(),[report,setReport]=useState<Report>(),[evidence,setEvidence]=useState<Evidence>();
  const [depositAmount,setDepositAmount]=useState('3000'),[refundAmount,setRefundAmount]=useState('30'),[withdrawAmount,setWithdrawAmount]=useState('30');
  const [member,setMember]=useState(''),[payout,setPayout]=useState(''),[question,setQuestion]=useState('核查消费确认、提现来源和收款地址变化，说明是否影响会员未消费额度，并寻找正常解释与反证。');
  const [moneyAction,setMoneyAction]=useState<'deposit'|'refund'|'withdraw'|undefined>(),[requestId,setRequestId]=useState('');
  const identity=useRef({datasetId,account});identity.current={datasetId,account};
  const management=isManagementRoute(route),merchantPage=role==='merchant',ordinary=!management;
  const home=ordinary&&['/consumer','/merchant','/'].includes(route);
  const autoConnected=useRef('');
  const ds=cfg?.datasets.find(d=>d.id===datasetId),query='?datasetId='+encodeURIComponent(datasetId);
  const nav=useCallback((path:string)=>{history.pushState({},'',path);setRoute(path);setEvidence(undefined);setMoneyAction(undefined);setNotice('');setError('');},[]);
  useEffect(()=>{const listener=()=>{setRoute(location.pathname==='/'?'/consumer':location.pathname);setEvidence(undefined);setMoneyAction(undefined);};addEventListener('popstate',listener);return()=>removeEventListener('popstate',listener);},[]);
  useEffect(()=>{if(route==='/merchant')setRole('merchant');else if(route==='/consumer')setRole('member');},[route]);
  useEffect(()=>{sessionStorage.setItem('gym-role',role);setMoneyAction(undefined);setEvidence(undefined);setChat([]);setChatInput('');},[role,account,datasetId]);
  useEffect(()=>{let cancelled=false;const load=()=>api<PublicConfig>('/config').then(c=>{if(cancelled)return;setCfg(c);setConfigError('');setDatasetId(current=>current||preferredGym(c.datasets)?.id||c.datasets[0]?.id||'');}).catch(e=>{if(!cancelled)setConfigError(e.message);});void load();const timer=setInterval(()=>void load(),15000);return()=>{cancelled=true;clearInterval(timer);};},[]);
  useEffect(()=>{if(ordinary&&cfg&&ds?.adapter!=='gym'){const gym=preferredGym(cfg.datasets);if(gym)setDatasetId(gym.id);}},[route,cfg,ds?.adapter]);
  const refresh=useCallback(async()=>{
    if(!datasetId)return;
    try{const o=await api<Overview>('/overview'+query);if(identity.current.datasetId!==datasetId)return;setOverview(o);
      if(account&&o.dataset.adapter==='gym'){const u=await api('/users/'+account+query);if(identity.current.datasetId!==datasetId||identity.current.account!==account)return;setUser(u);}else if(identity.current.account===account)setUser(undefined);
      if(identity.current.datasetId===datasetId&&identity.current.account===account)setDataError(o.checkpoint?.status==='error'?'链上同步中断，已保存的数据不能当作最新余额。':'');
    }catch(e){if(identity.current.datasetId===datasetId&&identity.current.account===account){setDataError('数据刷新失败，可能过时。恢复连接前不能判断余额或风险。');setUser(undefined);}throw e;}
  },[datasetId,account,query]);
  useEffect(()=>{setOverview(undefined);setUser(undefined);setDataError('');setNotice('');setJob(undefined);if(!route.startsWith('/reports/'))setReport(undefined);setEvidence(undefined);setMember(ds?.users?.[0]||'');setPayout(ds?.nextPayout||'');setRequestId('');setMoneyAction(undefined);
    autoConnected.current='';
    setQuestion(ds?.adapter==='erc20'?'比较评估日与此前7个完整日的转出规模和集中度，核验主要交易，限定补查实际接收地址，寻找正常解释与反证。':'核查消费确认、提现来源和收款地址变化，说明是否影响会员未消费额度，并寻找正常解释与反证。');
    if(walletChain!==undefined&&walletChain!==ds?.chainId){setAccount('');setWallet(undefined);setWalletChain(undefined);setLocalAccounts([]);setNotice('已切换场景，原账号连接已清除。');}
  },[datasetId]);
  useEffect(()=>{if(!datasetId)return;void refresh().catch(()=>{});const timer=setInterval(()=>void refresh().catch(()=>{}),5000);return()=>clearInterval(timer);},[datasetId,refresh]);
  useEffect(()=>{if(!route.startsWith('/reports/'))return;let cancelled=false;setReport(undefined);const load=()=>api<Report>('/reports/'+route.split('/')[2]).then(r=>{if(cancelled)return;if(!r)throw new Error('报告不存在。');setReport(r);setDatasetId(r.datasetId);}).catch(e=>{if(!cancelled)setError(e.message);});void load();const timer=setInterval(()=>void load(),5000);return()=>{cancelled=true;clearInterval(timer);};},[route]);
  useEffect(()=>{const injected=(window as any).ethereum;if(!injected?.on)return;const changed=()=>{setAccount('');setWallet(undefined);setWalletChain(undefined);setUser(undefined);setLocalAccounts([]);setNotice('钱包账户或网络已变更，请重新连接。');};injected.on('accountsChanged',changed);injected.on('chainChanged',changed);return()=>{injected.removeListener?.('accountsChanged',changed);injected.removeListener?.('chainChanged',changed);};},[]);
  async function act(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e:any){setNotice('');setError(walletError(e));}finally{setBusy(false);}}
  async function connectLocal(asMerchant=merchantPage){
    if(!cfg||ds?.chainId!==31337||!['127.0.0.1','localhost'].includes(location.hostname))throw new Error('演示账号仅允许用于本机测试场景。');
    const selectedId=ds.id,provider=new JsonRpcProvider(cfg.localRpc,31337,{staticNetwork:true,cacheTimeout:-1});
    if(Number(await provider.send('eth_chainId',[]))!==31337){provider.destroy();throw new Error('演示账号网络不正确。');}
    const signers=await provider.listAccounts();if(identity.current.datasetId!==selectedId){provider.destroy();return;}
    setLocalAccounts(signers.map(s=>s.address));setWallet(provider);setWalletChain(31337);setAccount(signers[asMerchant?0:1].address);setUser(undefined);
  }
  // Local demo login reads accounts only. It never signs a transaction automatically.
  useEffect(()=>{if(!ordinary||!cfg||!cfg.localTestWalletEnabled||ds?.chainId!==31337||account||wallet||busy)return;const key=ds.id+role;if(autoConnected.current===key)return;autoConnected.current=key;void connectLocal().catch(e=>setError(e.message));},[ordinary,role,datasetId,!!cfg,account,wallet,busy]);
  useEffect(()=>{if(!ordinary||!localAccounts.length||walletChain!==31337)return;if(account&&account!==localAccounts[0])lastMember.current=account;const next=merchantPage?localAccounts[0]:account===localAccounts[0]?(localAccounts.includes(lastMember.current)?lastMember.current:localAccounts[1]):account;if(next&&next!==account){setAccount(next);setUser(undefined);}},[role,localAccounts,account,ordinary,walletChain]);
  async function connectWallet(){const injected=(window as any).ethereum;if(!injected)throw new Error('没有检测到钱包；本地演示可以使用演示账号。');const provider=new BrowserProvider(injected);await provider.send('eth_requestAccounts',[]);const chain=Number((await provider.getNetwork()).chainId);if(chain!==ds?.chainId)throw new Error('钱包网络与当前健身房不一致，请切换后重连。');setWallet(provider);setWalletChain(chain);setLocalAccounts([]);setUser(undefined);setAccount(await (await provider.getSigner()).getAddress());}
  async function transact(method:string,args:any[],token=false){
    if(!ds?.escrow||!cfg||!wallet||!account||ds.chainId===1)throw new Error('请先连接当前健身房的账号。');
    assertIdentity(identity.current,ds.id,account);if(Number(await wallet.send('eth_chainId',[]))!==ds.chainId)throw new Error('钱包网络与健身房不一致。');
    const signer=await wallet.getSigner(account);assertIdentity(identity.current,ds.id,account);
    const contract=new Contract(token?ds.token:ds.escrow,token?cfg.tokenAbi:cfg.escrowAbi,signer),label:Record<string,string>={approve:'充值授权',deposit:'充值',refund:'退回余额',requestConsumption:'发送消费确认',confirmConsumption:'确认消费',rejectConsumption:'拒绝消费',withdraw:'提现',setPayoutAddress:'更新收款账户',cancelConsumption:'取消申请',expireConsumption:'清理过期申请'};
    setNotice('等待确认：'+(label[method]||'操作'));const tx=await contract[method](...args);setNotice('操作已发送，正在等待确认：'+tx.hash);
    const receipt=await tx.wait();if(receipt?.status!==1)throw new Error('操作未成功，请查看提示后重试。');setNotice('操作已完成：'+tx.hash);if(method!=='approve')setMoneyAction(undefined);
    try{const checkpoint=await api('/sync',{datasetId});if(checkpoint.status!=='ok')throw new Error('Sync interrupted');await refresh();}
    catch{setDataError('操作已确认，但余额刷新失败。请恢复连接后刷新，不要重复提交。');setNotice('操作已完成，但页面余额尚未更新，请勿重复提交。');}
  }
  function amount(text:string){if(!/^[1-9]\d*$/.test(text))throw new Error('请输入正整数健身币。');return BigInt(text);}
  async function deposit(){if(!cfg||!ds||!wallet)throw new Error('请先连接账号。');const n=amount(depositAmount);if(n%30n!==0n)throw new Error('充值数量需为 30 的整数倍，每次消费 30 币。');const signer=await wallet.getSigner(account),token=new Contract(ds.token,cfg.tokenAbi,signer);if(await token.allowance(account,ds.escrow)<n)await transact('approve',[ds.escrow,n],true);await transact('deposit',[n]);}
  async function investigate(){setJob(await api('/investigations',{datasetId,question}));setNotice('核查已开始，结果会自动保存。');}
  async function askAssistant(){
    const text=chatInput.trim(),asked=investigationQuestion(text,role,account),selected=datasetId;
    const next=await api('/investigations',{datasetId,question:asked});
    if(identity.current.datasetId!==selected)return;
    setJob(next);
    if(next.question!==asked){setNotice('当前健身房已有调查在进行，先展示该任务进度；你的新问题还未执行，请完成后再发送。');return;}
    setChat(current=>[...current,{jobId:next.id,question:text}]);setChatInput('');setNotice('AI 已收到问题，正在查询当前健身房记录。');
  }
  useEffect(()=>{
    if(!job||!['queued','running'].includes(job.status))return;
    let cancelled=false,inflight=false;const selected=datasetId;
    const timer=setInterval(async()=>{
      if(inflight)return;inflight=true;
      try{
        const next=await api('/investigations/'+job.id);
        if(cancelled||identity.current.datasetId!==selected)return;
        // Load the report before changing status: status changes clean up this effect.
        if(next.reportId){
          const result=await api<Report>('/reports/'+next.reportId);
          if(cancelled||identity.current.datasetId!==selected)return;
          setReport(result);setJob(next);
          setNotice(next.status==='complete'?'核查完成。':'AI 核查未完成，不能当作完整判断。');
          void refresh().catch(()=>{});
        }else setJob(next);
      }catch(e:any){if(!cancelled)setError(e.message);}finally{inflight=false;}
    },1500);
    return()=>{cancelled=true;clearInterval(timer);};
  },[job?.id,job?.status,datasetId]);
  useEffect(()=>{
    if(!job?.reportId||report?.id===job.reportId)return;
    let cancelled=false;const selected=datasetId;
    void api<Report>('/reports/'+job.reportId).then(result=>{if(!cancelled&&identity.current.datasetId===selected&&result.datasetId===selected)setReport(result);}).catch(e=>{if(!cancelled)setError('报告暂时无法读取：'+e.message);});
    return()=>{cancelled=true;};
  },[job?.reportId,datasetId]);
  useEffect(()=>{if(!job||!['complete','partial','failed'].includes(job.status))return;setChat(current=>current.map(item=>item.jobId!==job.id||item.reply?item:{...item,reply:job.status==='complete'&&report&&report.id===job.reportId?assistantReply(report):job.status==='complete'?undefined:'这次核查未完成，不能给出完整判断。请检查服务后重试。',report:report?.id===job.reportId?report:undefined}));},[job?.id,job?.status,report?.id]);
  const canWrite=writeReady({account,adapter:ds?.adapter,chainId:ds?.chainId,walletChain,dataError,configError,user,checkpoint:overview?.checkpoint});
  const merchant=canWrite&&account.toLowerCase()===ds?.merchant?.toLowerCase();
  const dataReady=!!overview&&overview.checkpoint?.status==='ok'&&overview.checkpoint?.coverageComplete&&!dataError&&!configError;
  const funding=fundingStatus(overview?.snapshot,dataReady),alerts=usefulAlerts(overview?.alerts||[],account,merchantPage).filter((item,index,all)=>!all.some((other,otherIndex)=>other.ruleId===item.ruleId&&other.metrics.user===item.metrics.user&&(other.window.to>item.window.to||other.window.to===item.window.to&&otherIndex>index)));
  const latest=dataReady?usableReport(overview?.reports||[],datasetId,overview?.checkpoint?.blockNumber):undefined;
  const pending=dataReady?overview?.businessSummary?.pending:undefined;
  const activeJob=overview?.latestJob&&['running','queued'].includes(overview.latestJob.status)?overview.latestJob:job&&['running','queued'].includes(job.status)?job:undefined;
  const memberNames=['商家','会员 A','会员 B','会员 C','原收款账户','新收款账户'];
  const localName=memberNames[localAccounts.findIndex(a=>a.toLowerCase()===account.toLowerCase())]||'已连接账号';
  const pageTitle=management?route.startsWith('/reports/')?'完整调查报告':route==='/cases'?'案例与报告':'调查管理':route==='/assistant'?'AI 健身助手':route==='/records'?(merchantPage?'交易记录':'消费记录'):merchantPage?'收款结算':'我的健身卡';
  async function showEvidence(ref:string){setEvidence(await api('/evidence/'+ref));}
  const goBusiness=(path:string)=>{if(ds?.adapter!=='gym'&&cfg){const gym=preferredGym(cfg.datasets);if(gym)setDatasetId(gym.id);}if(path==='/consumer')setRole('member');if(path==='/merchant')setRole('merchant');nav(path);};
  function connection(){return <details className="account-settings"><summary><span className="avatar">{merchantPage?'商':'会'}</span><span>{account?(localAccounts.length?localName:merchantPage?'商家视图':'会员视图'):'连接账号'}</span><span aria-hidden="true">⌄</span></summary><div className="account-menu"><strong>当前身份 · {merchantPage?'商家':'会员'}</strong><div className="role-switch"><button disabled={busy} className={!merchantPage?'selected':''} onClick={e=>{goBusiness('/consumer');e.currentTarget.closest('details')?.removeAttribute('open');}}>会员</button><button disabled={busy} className={merchantPage?'selected':''} onClick={e=>{goBusiness('/merchant');e.currentTarget.closest('details')?.removeAttribute('open');}}>商家</button></div><small>切换视图不授予钱包权限。本地演示会切换测试账号。</small>{localAccounts.length>0&&!merchantPage&&<label>演示会员<select aria-label="演示会员" disabled={busy} value={account} onChange={e=>{setAccount(e.target.value);setUser(undefined);setNotice('');setError('');}}>{localAccounts.slice(1,4).map((a,i)=><option key={a} value={a}>会员 {['A','B','C'][i]}</option>)}</select></label>}{ds?.chainId===31337&&cfg?.localTestWalletEnabled&&<button disabled={busy} onClick={()=>void act(()=>connectLocal())}>使用演示账号</button>}{ds?.adapter==='gym'&&<button disabled={busy} onClick={()=>void act(connectWallet)}>连接我的钱包</button>}{account&&<details><summary>钱包信息</summary><small className="mono">{account}</small></details>}<button disabled={busy} onClick={e=>{nav('/admin');e.currentTarget.closest('.account-settings')?.removeAttribute('open');}}>研究与开发演示</button></div></details>;}
  function activity(full=false){const events=merchantPage?overview?.events.filter(e=>['Withdrawn','ConsumptionRequested','ConsumptionConfirmed','ConsumptionRejected','ConsumptionCancelled','ConsumptionExpired','PayoutAddressChanged'].includes(e.name))||[]:memberEvents(overview?.events||[],account);return <section className="panel"><div className="section-head"><h2>{full?(merchantPage?'收款与结算流水':'我的消费与额度记录'):merchantPage?'最近收款记录':'我的最近记录'}</h2>{!full&&<button className="text-button" onClick={()=>goBusiness('/records')}>查看全部 →</button>}</div>{full&&<p className="muted">从最近保存的 {overview?.events.length??0} 条健身房事件中筛选{merchantPage?'商家业务':'当前会员'}记录，非完整历史。原始记录保留在后台。</p>}{!dataReady?<p className="muted">记录暂时无法获取，不代表没有消费。</p>:!account?<p className="muted">连接账号后查看自己的记录。</p>:!events.length?<p className="muted">最近保存的记录中没有相关活动。</p>:<div className="activity-list">{events.slice(full?0:-5).reverse().map(e=><div className="activity-row" key={e.id}><div><strong>{names[e.name]||'账户变更'}</strong><small className="block">{date(e.timestamp)}{merchantPage&&e.args.user?' · 会员 '+short(e.args.user):''}</small></div><span>{e.args.amount?formatUnits(e.args.amount,ds?.decimals??0)+' 币':'—'}</span><details className="receipt"><summary>凭证</summary><p className="mono">编号：{e.txHash}</p><button onClick={()=>void act(()=>showEvidence(e.id))}>查看依据</button></details></div>)}</div>}</section>;}
  function protection(){return <section className={'panel protection '+funding.tone}>
    <div className="section-head"><div><span className="eyebrow">AI 助手 · {merchantPage?'资金与经营提醒':'我的额度保障'}</span><h2>{funding.title}</h2></div><button className="text-button" onClick={()=>goBusiness('/assistant')}>问问 AI 助手 →</button></div>
    <p>{funding.text}</p>{dataReady&&alerts.slice(0,1).map(a=><div className="plain-alert" key={a.id}><strong>{a.copy.title}</strong><p>{a.copy.text}</p><small>{a.copy.action}</small></div>)}
    {dataReady&&!alerts.length&&<p className="muted">当前规则未发现需要提示的变化，不代表完全没有风险。</p>}
    <div className="ai-status"><span className="status-dot"/>{investigationNotice(dataReady,!!activeJob,overview?.latestJob,latest,!!overview?.backgroundMonitoring)}</div>
    {latest&&<p className="ai-brief">上次 AI 核查：{latest.review?'报告包含复核更正，详细结果需结合更正阅读。':assistantReply(latest).slice(0,110)+(assistantReply(latest).length>110?'…':'')}</p>}
    <small className="block">账目与规则提示不等于 AI 判断。{latest?'已有报告：'+new Date(latest.generatedAt).toLocaleString('zh-CN')+'，不覆盖之后的变化。':'尚无已完成的 AI 报告。'}</small>
  </section>;}
  function assistantPage(){
    const task=activeJob||job||overview?.latestJob;
    const response=chat.at(-1)?.report;
    const result=dataReady?(response?.datasetId===datasetId?response:latest):undefined;
    const accepted=result?.status==='complete'&&result.mode==='llm';
    const refs=(ids:string[])=>ids.map(ref=><button className="evidence-button" key={ref} onClick={()=>void act(()=>showEvidence(ref))}>查看证据</button>);
    return <div className="assistant-grid"><section className="panel chat-panel"><div className="section-head"><div><span className="eyebrow">不懂链上数据？直接问。</span><h2>陪你查清楚</h2></div><span className="status-pill">{activeJob?'正在核查':'调查助手'}</span></div><p className="context-note">当前健身房：{ds?.name} · {merchantPage?'商家视角':'会员视角'}<br/>只读调查，不代替你确认消费或转账。</p>
      <div className="chat-history" aria-live="polite"><div className="message assistant-message"><strong>今天链不练 AI</strong><p>我能核查消费确认、资金覆盖、提现来源和收款账户变化。你想查哪一件事？</p></div>{chat.map(item=><React.Fragment key={item.jobId}><div className="message user-message"><strong>你</strong><p>{item.question}</p></div><div className="message assistant-message"><strong>今天链不练 AI</strong><p>{item.reply||'正在取证与分析，尚未形成结论。'}</p>{item.report&&<small>依据截至区块 #{item.report.asOfBlock}，不是未来经营保证。</small>}</div></React.Fragment>)}</div>
      {!chat.length&&<div className="starter-questions">{starterQuestions[role].map(text=><button key={text} disabled={busy||!!activeJob} onClick={()=>setChatInput(text)}>{text} ↗</button>)}</div>}
      {task&&<details className="investigation-progress" open={!!activeJob}><summary>{jobLabels[task.status]||'核查状态待确认'} · 已记录 {task.toolRuns?.length??0} 次工具调用</summary>{task.toolRuns?.length?<ol>{task.toolRuns.map((t:any)=><li key={t.id}>{toolNames[t.name]||'核对链上信息'} · {t.status==='ok'?'已完成':'未成功'}<small className="block">{t.summary}</small></li>)}</ol>:<p className="muted">{activeJob?'正在等待分析工具返回结果。':'没有工具调用记录。'}</p>}{task.status==='failed'&&<p className="error">调查中断，请检查模型与数据服务后重试。</p>}</details>}
      <form className="chat-composer" onSubmit={event=>{event.preventDefault();void act(askAssistant);}}><label htmlFor="assistant-question">你想核查什么？</label><textarea id="assistant-question" aria-label="向 AI 助手提问" placeholder="比如：最近的提现会影响我的余额吗？" maxLength={800} disabled={busy||!!activeJob} value={chatInput} onChange={event=>setChatInput(event.target.value)}/><div className="section-head"><small>每次独立取证，报告自动保存。<br/>交易记录与问题会交由 DeepSeek 核查。</small><button className="primary" disabled={busy||!dataReady||!!activeJob||!chatInput.trim()} type="submit">{activeJob?'核查中…':'发送并核查'}</button></div></form>
    </section><div className="assistant-results"><section className={'panel protection '+funding.tone}><div className="section-head"><h2>现在的资金状态</h2><span className="status-pill">{dataReady?'账目核对':'等待数据'}</span></div><strong>{funding.title}</strong><p>{funding.text}</p>{dataReady&&<div className="funding-numbers"><div><small>托管资产</small><b>{overview?.snapshot?.assets} 币</b></div><div><small>会员未用额度（总计）</small><b>{overview?.snapshot?.userCredit} 币</b></div><div><small>已结算待提现</small><b>{overview?.snapshot?.revenue} 币</b></div></div>}<small>最新账目截至区块 #{overview?.checkpoint?.blockNumber??'待获取'}；与下方历史报告时间可能不同。</small>{dataReady&&overview?.snapshot?.evidenceId&&<details className="more-details"><summary>查看账目依据</summary>{refs([overview.snapshot.evidenceId])}</details>}</section>
      <section className="panel"><h2>需要留意的变化</h2>{!dataReady?<p className="muted">暂时无法核查变化。</p>:alerts.length?alerts.map(a=><div className="plain-alert" key={a.id}><strong>{a.copy.title}</strong><p>{a.copy.text}</p><small>{a.copy.action}</small><details className="more-details"><summary>核对提示依据（规则筛选，非 AI 结论）</summary>{refs(a.evidenceIds)}</details></div>):<p className="muted">当前规则没有命中提醒，不代表没有风险。</p>}</section>
      <section className="panel assistant-report"><div className="section-head"><h2>{response?'本次核查结果':'已有 AI 核查'}</h2>{accepted&&<span className="status-pill">有证据可查</span>}</div>{activeJob&&<p className="context-note">新调查正在进行，下方已有报告不能当作新问题的回答。</p>}<p className="muted">{investigationNotice(dataReady,!!activeJob,job||overview?.latestJob,latest,!!overview?.backgroundMonitoring)}</p>{result?<><small>健身房整体调查 · {new Date(result.generatedAt).toLocaleString('zh-CN')} · 截至区块 #{result.asOfBlock}</small>{!accepted?<p className="error">AI 调查未完成，不能提供完整分析结论。</p>:<>{result.review?.notes.length?<div className="review-summary"><h3>先看复核更正</h3><p className="muted">人工开发复核，不是第二个 Agent。更正优先于原报告。</p>{result.review.notes.map((note,i)=><details key={i} className="more-details"><summary>{i===0?'资金与时间范围更正':'补充说明 '+(i+1)}</summary><p>{note.text}</p>{refs(note.evidenceIds)}</details>)}</div>:<><h3>对你的影响</h3><p>{result.consumerImpact}</p></>}<details className="more-details"><summary>事实、解释与未知</summary>{result.findings.map((f,i)=><article className="finding" key={i}><span className={'type '+f.type}>{({fact:'链上事实',inference:'分析推断',unknown:'尚待核实'})[f.type]}</span><p>{f.text}</p>{refs(f.evidenceIds)}</article>)}{result.hypotheses.filter((_,i)=>!result.review?.excludedHypotheses.includes(i)).map((h,i)=><article className="finding" key={'h'+i}><strong>可能解释，非定论</strong><p>{h.explanation}</p><small>仍待核查：{h.unresolved.join('；')||'需结合线下经营核实'}</small>{refs([...new Set([...h.supportingEvidenceIds,...h.contradictingEvidenceIds])])}</article>)}</details><h3>可以怎么做</h3><ul>{result.recommendations.slice(0,3).map((text,i)=><li key={i}>{text}</li>)}</ul><details className="more-details"><summary>本次调查的限制</summary><ul>{result.limitations.map((text,i)=><li key={i}>{text}</li>)}</ul></details><div className="buttons"><a className="button" href={'/api/reports/'+result.id+'/export?format=md'} download>下载核查报告</a><button className="text-button" onClick={()=>nav('/reports/'+result.id)}>技术原稿与工具轨迹</button></div></>}</>:<p className="muted">还没有可用的已完成报告。可以从左边发起核查，不用填写链上地址。</p>}</section>
    </div></div>;
  }
  function eventsTable(){return <><p className="muted">已保存 {overview?.totalEventCount??'待获取'} 条事件，页面显示最近 {overview?.events.length??0} 条；指标使用完整保存窗口。</p><div className="table-scroll"><table><thead><tr><th>行为</th><th>金额 / 对象</th><th>区块与时间</th><th>凭证</th></tr></thead><tbody>{overview?.events.slice().reverse().map(e=><tr key={e.id}><td>{e.name==='Transfer'&&ds?.adapter==='erc20'?(e.args.value==='0'?'零金额日志':e.args.from.toLowerCase()===ds.target?.toLowerCase()?'目标转出':'目标转入'):names[e.name]||e.name}</td><td>{e.args.amount||e.args.value?formatUnits(e.args.amount||e.args.value,ds?.decimals??0):short(e.args.newAddress)} {e.args.amount||e.args.value?ds?.tokenSymbol:''}<br/><small>{e.name==='Transfer'&&ds?.adapter==='erc20'?short(e.args.from)+' → '+short(e.args.to):short(e.args.user||e.args.from||e.args.operator)}</small></td><td>#{e.blockNumber}<br/><small>{date(e.timestamp)} · {e.finality}</small></td><td><button onClick={()=>void act(()=>showEvidence(e.id))}>查看证据</button></td></tr>)}</tbody></table></div></>;}
  function reportView(r:Report){return <section className="panel report"><div className="section-head"><h2>{r.headline}</h2><span className="badge">{r.mode==='llm'?'AI 工具调查':'规则降级'} · {r.status}</span></div><p className="muted">网络 {r.chainId} · {origins[r.dataOrigin]} · 截止区块 #{r.asOfBlock} · {new Date(r.generatedAt).toLocaleString('zh-CN')}</p><h3>权益影响</h3><p>{r.consumerImpact}</p>{r.review&&<section className="finding" aria-label="开发验收复核"><h3>开发验收复核说明</h3><p className="muted">非 AI 原稿、非第二 Agent。原稿保留，以下更正优先，不保证现实经营安全。</p>{r.review.notes.map((n,i)=><div key={i}><p>{n.text}</p><div className="buttons">{n.evidenceIds.map(ref=><button key={ref} onClick={()=>void act(()=>showEvidence(ref))}>复核证据 {short(ref)}</button>)}</div></div>)}</section>}<h3>事实、推断与未知</h3>{r.findings.map((f,i)=><article className="finding" key={i}><span className={'type '+f.type}>{({fact:'事实',inference:'推断',unknown:'未知'})[f.type]}</span><p>{f.text}</p><div className="buttons">{f.evidenceIds.map(ref=><button key={ref} onClick={()=>void act(()=>showEvidence(ref))}>证据 {short(ref)}</button>)}</div></article>)}<h3>解释与反证</h3>{r.hypotheses.map((h,i)=><article className="finding" key={i}>{r.review?.excludedHypotheses.includes(i)&&<p className="error">原始假设未通过开发复核，不采用为判断依据。</p>}<b>{h.explanation}</b><p>仍待核查：{h.unresolved.join('；')||'无额外说明'}</p><div className="buttons">{[...h.supportingEvidenceIds,...h.contradictingEvidenceIds].map((ref,j)=><button key={ref+j} onClick={()=>void act(()=>showEvidence(ref))}>{j<h.supportingEvidenceIds.length?'支持':'反证'} {short(ref)}</button>)}</div></article>)}<h3>建议</h3><ul>{r.recommendations.map((s,i)=><li key={i}>{s}</li>)}</ul><h3>限制</h3><ul>{r.limitations.map((s,i)=><li key={i}>{s}</li>)}</ul><details><summary>技术附件与工具轨迹</summary>{r.analysis&&<pre>{JSON.stringify(r.analysis,null,2)}</pre>}<ol>{r.toolRuns.map(t=><li key={t.id}><b>{t.name}</b> · {t.status} · {t.summary}<small className="block">{JSON.stringify(t.arguments)}</small></li>)}</ol></details><div className="buttons"><a className="button" href={'/api/reports/'+r.id+'/export?format=md'} download>下载报告</a><a className="button" href={'/api/reports/'+r.id+'/export?format=json'} download>下载原始 JSON</a></div></section>;}
  return <div className="app"><div className="topbar"><div className="topbar-inner"><a className="brand" href={merchantPage?'/merchant':'/consumer'} onClick={e=>{e.preventDefault();if(!busy)goBusiness(merchantPage?'/merchant':'/consumer');}}><span className="brand-mark" aria-hidden="true">链</span><span>今天链不练<small>每次确认，才结一笔</small></span></a><nav aria-label="主要导航"><button disabled={busy} className={home?'selected':''} aria-current={home?'page':undefined} onClick={()=>goBusiness(merchantPage?'/merchant':'/consumer')}>{merchantPage?'收款结算':'我的健身卡'}</button><button disabled={busy} className={route==='/records'?'selected':''} aria-current={route==='/records'?'page':undefined} onClick={()=>goBusiness('/records')}>{merchantPage?'交易记录':'消费记录'}</button><button disabled={busy} className={route==='/assistant'?'selected':''} aria-current={route==='/assistant'?'page':undefined} onClick={()=>goBusiness('/assistant')}>AI 助手</button></nav>{connection()}</div></div><main>
    <header><div><span className="eyebrow">{management?'研究与开发演示 · 日常使用无需进入这里':route==='/assistant'?'少一点猜测，多一点依据':merchantPage?'经营工作台':'安心办卡，明白消费'}</span><h1>{pageTitle}</h1></div><span className="badge">{ds?origins[ds.dataOrigin]:'正在准备'}</span></header>
    {notice&&<div className="notice" role="status">{management?notice:notice.replace(/0x[0-9a-fA-F]{64}/g,'').replace(/：\s*$/,'')}</div>}{error&&<div className="error" role="alert">{error}</div>}{(configError||dataError)&&<div className="error" role="alert">{management?(configError||dataError):dataError.startsWith('操作已确认')?dataError:'暂时无法获取可靠余额，操作已暂停。请恢复服务后重试。'}</div>}
    {ordinary&&!ds&&<section className="panel"><h2>正在准备你的健身卡</h2><p>连接成功后，余额和待办会自动显示。</p></section>}
    {ordinary&&ds&&ds.adapter!=='gym'&&<section className="panel"><p>这里是健身卡服务，需要可用的健身房场景。公共链研究请进入调查管理。</p></section>}
    {home&&ds?.adapter==='gym'&&!merchantPage&&<>
      <section className="card-hero"><div><span className="eyebrow">我的剩余次数</span><div className="hero-number">{canWrite?user.remainingVisits:account?'—':'待连接'}<small>次</small></div><p>未消费额度 <strong>{canWrite?user.balance:'待核查'}</strong> 健身币</p><small>{canWrite&&user.validUntil?'有效期至 '+new Date(user.validUntil*1000).toLocaleDateString('zh-CN'):canWrite?'还没有充值，充入后开始一年有效期':'正在获取账户记录'} · 每次 30 币</small></div><div className="hero-actions"><button className="primary" disabled={!canWrite||busy} onClick={()=>setMoneyAction(moneyAction==='deposit'?undefined:'deposit')}>充值</button><button disabled={!canWrite||busy||BigInt(user?.balance||'0')===0n} onClick={()=>setMoneyAction(moneyAction==='refund'?undefined:'refund')}>退回未用额度</button><small>余额留在托管账户<br/>消费确认后才结给商家</small></div></section>
      <section className="panel todo"><div className="section-head"><h2>现在需要你处理</h2>{canWrite&&<span className="status-pill">{user.activeRequest?'1 项待确认':'没有待办'}</span>}</div>{!canWrite?<p className="muted">账户记录尚未获取，不能判断是否有待确认消费。</p>:user.activeRequest?<><p className="todo-title">健身房申请结算一次服务 · {user.activeRequest.amount} 币</p><p className="muted">只有确实使用了服务才确认。确认前不扣你的额度。</p><div className="buttons"><button className="primary" disabled={busy} onClick={()=>void act(()=>transact('confirmConsumption',[user.activeRequest.id]))}>我已使用，确认消费</button><button disabled={busy} onClick={()=>void act(()=>transact('rejectConsumption',[user.activeRequest.id]))}>没有使用，拒绝</button></div><details><summary>申请详情</summary><p>申请编号 {user.activeRequest.id}，到期时间 {date(user.activeRequest.expiresAt)}。</p><button disabled={busy} onClick={()=>void act(()=>transact('expireConsumption',[user.activeRequest.id]))}>清理已过期申请</button><p className="muted">只有到期后才能清理，过期不扣费。</p></details></>:<p className="muted">没有待确认消费，安心去练吧。</p>}</section>
      {protection()}{activity()}
    </>}
    {home&&merchantPage&&ds?.adapter==='gym'&&<>
      <section className="stats"><article><label>今天已确认收入</label><strong>{dataReady?overview?.businessSummary?.todayRevenue??'待获取':'待核查'} <small>币</small></strong></article><article className="highlight-stat"><label>现在可以提现</label><strong>{dataReady?overview?.snapshot?.revenue:'待核查'} <small>币</small></strong></article><article><label>等待会员确认</label><strong>{pending?pending.length:'待核查'} <small>笔</small></strong></article></section>
      {!merchant&&account&&<p className="muted">当前账号没有商家操作权限。演示模式可从账号设置切回商家，钱包模式需连接商家账号。</p>}
      <div className="business-grid"><section className="panel"><h2>发起一次健身消费</h2><p className="muted">发出申请不扣费，会员确认后才计入收入。</p><div className="forms stacked"><label>选择会员{ds.users?.length?<select aria-label="消费会员" disabled={busy} value={member} onChange={e=>setMember(e.target.value)}>{ds.users.map((a,i)=><option key={a} value={a}>会员 {['A','B','C'][i]||i+1}</option>)}</select>:<input aria-label="会员地址" value={member} onChange={e=>setMember(e.target.value)}/>}</label><p className="muted">单次健身 · 30 币，凭证编号由系统自动生成。</p><button className="primary" disabled={!merchant||busy} onClick={()=>void act(async()=>{if(!isAddress(member))throw new Error('请选择有效会员。');await transact('requestConsumption',[member,id('visit-'+crypto.randomUUID())]);})}>发送消费确认 · 30 币</button></div></section>
      <section className="panel"><h2>提取已结算收入</h2><p className="muted">未消费的会员额度不能提现。只有确认消费的收入才可提取。</p><div className="withdraw-overview"><span className="eyebrow">可提现</span><strong>{dataReady?overview?.snapshot?.revenue:'—'} <small>健身币</small></strong></div><button className="primary" disabled={!merchant||busy} onClick={()=>setMoneyAction('withdraw')}>申请提现</button><small className="block">{dataReady&&BigInt(overview?.snapshot?.revenue||'0')===0n?'暂时没有已结算收入，可以在弹窗查看规则。':'提现会生成可核查的记录。'}</small><details className="more-details"><summary>收款账户设置</summary><p className="mono">当前账户：{overview?.snapshot?.payout??'待核查'}</p><label className="block">新收款账户<input aria-label="新收款账户" value={payout} onChange={e=>setPayout(e.target.value)}/></label><button disabled={!merchant||busy} onClick={()=>void act(async()=>{if(!isAddress(payout))throw new Error('收款账户格式错误。');await transact('setPayoutAddress',[payout]);})}>更新收款账户</button></details></section></div>
      <section className="panel"><h2>待会员确认</h2>{!pending?<p className="muted">正在核对消费申请。</p>:!pending.length?<p className="muted">目前没有待确认的申请。</p>:pending.map(e=><div className="activity-row" key={e.id}><div><strong>会员 {short(e.args.user)} · {e.args.amount} 币</strong><small className="block">申请 {e.args.id} · {date(e.timestamp)}</small></div><button disabled={!merchant||busy} onClick={()=>void act(()=>transact('cancelConsumption',[amount(e.args.id)]))}>取消申请</button></div>)}<details className="more-details"><summary>按编号取消其他申请</summary><div className="forms"><label>申请编号<input aria-label="申请编号" value={requestId} onChange={e=>setRequestId(e.target.value)} inputMode="numeric"/></label><button disabled={!merchant||busy} onClick={()=>void act(()=>transact('cancelConsumption',[amount(requestId)]))}>取消申请</button></div></details></section>{protection()}{activity()}
    </>}
    {ordinary&&ds?.adapter==='gym'&&route==='/records'&&activity(true)}
    {ordinary&&ds?.adapter==='gym'&&route==='/assistant'&&assistantPage()}
    {management&&<><div className="admin-nav"><button className={route!=='/cases'?'primary':''} onClick={()=>nav('/admin')}>调查工作台</button><button className={route==='/cases'?'primary':''} onClick={()=>nav('/cases')}>案例与报告</button></div><section className="panel admin-controls"><h2>选择调查案例</h2><p className="muted">这里保留研究与开发演示功能，日常办卡无需进入。管理入口只是界面分区，尚未实现生产级管理员登录。</p><div className="toolbar"><label>调查案例<select aria-label="调查案例" disabled={busy} value={datasetId} onChange={e=>{setDatasetId(e.target.value);setError('');if(route.startsWith('/reports/'))nav('/admin');}}>{cfg?.datasets.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button disabled={busy||!datasetId} onClick={()=>void act(async()=>{await api('/sync',{datasetId});await refresh();})}>刷新调查记录</button>{ds?.adapter==='gym'&&<><button disabled={busy} onClick={()=>nav('/consumer')}>预览会员页面</button><button disabled={busy} onClick={()=>nav('/merchant')}>预览商家页面</button></>}</div><details><summary>网络与数据范围</summary><p>网络 {ds?.chainId} · 数据截止 #{overview?.checkpoint?.blockNumber??'未获取'} · {dataReady?'已同步（不等于无风险）':'同步未完成或中断'}</p>{ds?.adapter==='erc20'&&<p>固定历史案例：{ds.analysisWindow?new Date(ds.analysisWindow.from*1000).toISOString().slice(0,10)+' UTC':'待获取'}，此前至少 {ds.baselineDays??7} 个完整日为基线；不是实时监控。采集时间 {ds.collection?.capturedAt??'未知'}。</p>}<p>指标以完整保存窗口计算，原始金额保留最小单位。{ds?.dataOrigin==='local-chain'?'当前为本地人为演示，不是公共以太坊交易。':''}</p></details></section>
      {(route==='/admin'||route==='/investigations')&&<><section className="panel"><div className="section-head"><h2>异动调查</h2><span className="muted">提醒不是跑路认定</span></div>{overview?.alerts.map(a=><article className="alert" key={a.id}><b>{a.ruleId} · {a.title}</b><p>{Object.entries(a.metrics).map(([k,v])=>metricLabel(k,v,ds)).join('；')}</p></article>)}{!overview?.alerts.length&&<p className="muted">当前没有规则提醒；请同时核对数据覆盖。</p>}<label className="block">调查问题<textarea aria-label="调查问题" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000}/></label><button className="primary" disabled={busy||!dataReady||!!activeJob} onClick={()=>void act(investigate)}>开始调查</button>{(job||overview?.latestJob)&&<div className="task"><b>{jobLabels[(job||overview?.latestJob).status]||'任务状态待核查'}</b><details><summary>查看实际工具调用</summary><ol>{(job||overview?.latestJob).toolRuns?.map((t:any)=><li key={t.id}>{t.name} · {t.summary}</li>)}</ol></details>{(job||overview?.latestJob).reportId&&<button onClick={()=>nav('/reports/'+(job||overview?.latestJob).reportId)}>查看调查报告</button>}</div>}</section><details className="panel"><summary>原始交易时间线</summary>{eventsTable()}</details>{report&&reportView(report)}</>}
      {route==='/cases'&&<section className="panel"><h2>案例与已保存报告</h2>{cfg?.datasets.map(d=><article className="finding" key={d.id}><b>{d.name}</b><p>{origins[d.dataOrigin]} · {d.adapter==='gym'?'健身房业务':'真实公共链研究'}</p><button onClick={()=>{setDatasetId(d.id);nav('/admin');}}>打开案例</button></article>)}<h3>当前案例的报告</h3>{overview?.reports.map(r=><article className="finding" key={r.id}><b>{r.headline}</b><p>{r.mode==='llm'?'AI 核查':'规则降级'} · {r.status} · #{r.asOfBlock}</p><button onClick={()=>nav('/reports/'+r.id)}>打开报告</button></article>)}</section>}
      {route.startsWith('/reports/')&&report&&reportView(report)}
    </>}
    {moneyAction&&<Modal title={moneyAction==='deposit'?'充值健身币':moneyAction==='refund'?'退回未消费额度':'提取已结算收入'} busy={busy} onClose={()=>{setMoneyAction(undefined);setError('');}}><p className="muted">{moneyAction==='deposit'?'钱包可用：'+(canWrite?user.wallet:'待核查')+' 币。3000 币可消费 100 次；充值需为 30 的整数倍。':moneyAction==='refund'?'可退回：'+(canWrite?user.balance:'待核查')+' 币。退回你的钱包，不撤销已确认的消费。':'可提现：'+(dataReady?overview?.snapshot?.revenue:'待核查')+' 币。不能提取会员未使用的额度。'}</p>{moneyAction==='withdraw'&&dataReady&&BigInt(overview?.snapshot?.revenue||'0')===0n&&<p className="context-note">暂时没有可提现收入，等待会员确认真实消费后再来。</p>}<form onSubmit={event=>{event.preventDefault();void act(moneyAction==='deposit'?deposit:()=>transact(moneyAction==='refund'?'refund':'withdraw',[amount(moneyAction==='refund'?refundAmount:withdrawAmount)]));}}><label className="block">{moneyAction==='deposit'?'充值数量':moneyAction==='refund'?'退回数量':'提现数量'}<input autoFocus aria-label={moneyAction==='deposit'?'充值数量':moneyAction==='refund'?'退回数量':'提现数量'} value={moneyAction==='deposit'?depositAmount:moneyAction==='refund'?refundAmount:withdrawAmount} onChange={event=>moneyAction==='deposit'?setDepositAmount(event.target.value):moneyAction==='refund'?setRefundAmount(event.target.value):setWithdrawAmount(event.target.value)} disabled={busy} inputMode="numeric"/></label>{error&&<p className="error" role="alert">{error}</p>}{busy&&<p role="status">正在等待链上确认，请勿重复操作。</p>}<div className="buttons"><button type="button" disabled={busy} onClick={()=>{setMoneyAction(undefined);setError('');}}>取消</button><button type="submit" className="primary" disabled={busy||(moneyAction==='withdraw'?!merchant||BigInt(overview?.snapshot?.revenue||'0')===0n:!canWrite)}>{busy?'正在处理…':moneyAction==='deposit'?'确认充值':moneyAction==='refund'?'确认退回':'确认提现'}</button></div></form><small>健身币是固定演示额度，不与人民币兑换，不随商家热度升值。</small></Modal>}
    {evidence&&<Modal title={management?'证据详情':'核查依据'} onClose={()=>setEvidence(undefined)}><div className="evidence" aria-label="证据详情"><p>核查时间：{new Date(evidence.capturedAt).toLocaleString('zh-CN')}。{evidence.coverage.complete?'本条记录已取得，仍需结合调查范围理解。':'本条证据覆盖不完整。'}</p><p>账本截至区块 #{evidence.asOfBlock} · 网络 {evidence.chainId}</p>{evidence.txHash&&<p className="mono">凭证编号：{evidence.txHash}</p>}{evidence.explorerUrl&&<a href={evidence.explorerUrl} target="_blank" rel="noreferrer">在公开账本核查</a>}<details open={management}><summary>原始凭证（技术资料）</summary><pre>{JSON.stringify(evidence,null,2)}</pre></details></div></Modal>}
    <footer>{ordinary?'健身币仅供本地演示，不代表人民币。消费请本人确认；资金覆盖不等于经营无风险。':'完整数据、模型原稿和证据保留在后台。异常不是犯罪结论；公开链研究不开放签名。'}</footer>
  </main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
