import {useEffect,useRef,useState} from 'react';
import {formatUnits} from 'ethers';
import type {ResearchOverview,ResearchRun,ResearchCase} from '../../shared/research';
import {exactTokenAmount} from '../../shared/research';
import {percentBps} from '../../shared/flow-view';
import {PlainReportCard} from './plain-report';

async function researchApi<T>(path='',body?:unknown):Promise<T>{const r=await fetch('/api/research'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'公共链案例暂时不可用。');return j.data;}
const toolLabel:Record<string,string>={list_events:'读取评估日与历史基线',compute_metrics:'独立重算指标',verify_transaction:'在线核对交易收据',trace_recipient:'补查接收账户'};
const short=(a:string)=>a.slice(0,6)+'…'+a.slice(-4);
const date=(n:number)=>new Date(n*1000).toISOString().slice(0,10)+' UTC';
function PublicCase({c,pending,disabled,onRun}:{c:ResearchCase;pending:boolean;disabled:boolean;onRun:()=>void}){
  const run=c.run,metrics=c.metrics;
  return <><div className="public-case-notice"><strong>以太坊主网 · 只读历史研究</strong><p>这些是真实公开地址的 USDC 流水，不属于健身房，也不会改变会员或商家的余额。评估日：{date(c.dataset.analysisWindow!.from)}。</p></div><PlainReportCard summary={c.summary}/><div className="research-action"><button className="primary" disabled={pending||disabled||run?.status==='investigating'||run?.status==='reviewing'} onClick={onRun}>{pending?'正在启动…':run?.status==='investigating'?'调查员正在取证…':run?.status==='reviewing'?'复核员独立核查…':run?'重新运行只读调查':'运行双 Agent 调查'}</button><span className="subtle">只读查询，没有付款、签名或冻结权限。</span></div>
    <section className="research-details" data-testid="public-case-evidence"><div className="section-title"><h3>调查依据与智能体分析</h3><a className="link" href={'/api/research/cases/'+encodeURIComponent(c.id)+'/export'}>导出公开案例证据</a></div><div className="analysis-status"><span>公开以太坊主网（chainId 1）</span><span>{run?.online.status==='verified'?'本次在线样本核验成功':run?.online.status==='failed'?'本次在线核验未完成':'尚未完成本次在线核验'}</span><span>历史索引，不是实时商家数据</span></div>{run?.error&&<p className="warning" role="alert">{run.error}</p>}
    <div className="quant-grid"><div><strong>{exactTokenAmount(metrics.current.total,metrics.decimals)}</strong><small>评估日转出 / USDC</small></div><div><strong>{metrics.relativeTotalBps===null?'无法比较':formatUnits(metrics.relativeTotalBps,4)+' 倍'}</strong><small>相对此前七日日均</small></div><div><strong>{percentBps(metrics.current.singleConcentrationBps)}</strong><small>最大单笔占当天转出的比例</small></div><div><strong>{metrics.current.count}</strong><small>评估日转出日志数（含零金额）</small></div></div>
    <p className="subtle">USDC 按 6 位小数展示；未接入市价，不换算人民币或美元报价。阈值用于研究线索，不是风险预测模型。</p>
    <div className="agent-grid">{run?.stages.length?run.stages.map(s=><section className="agent" key={s.name}><div className="agent-title"><strong>{s.name==='investigator'?'调查 Agent':'独立复核 Agent'}</strong><span>{s.status==='complete'?'已完成':s.status==='failed'?'未完成':'工作中'}</span></div><p className="subtle">{s.model} · 实际工具调用 {s.toolRuns.length} 次</p><div className="tool-list">{s.toolRuns.map(t=><span key={t.id}>{t.status==='ok'?'✓':'!'} {toolLabel[t.name]||t.name}</span>)}</div>{s.result?<><h4>本次判断</h4><p>{s.result.summary}</p><details><summary>支持线索、正常解释与证据缺口</summary>{s.result.observations.map((o,i)=><p key={i}>{o.type==='unknown'?'尚无法验证：':'证据支持的推断：'}{o.text}<small>证据：{o.evidenceIds.join('、')||'未知项，没有已验证证据'}</small></p>)}<h4>仍需核实的正常解释</h4>{s.result.alternatives.map((a,i)=><p key={i}>{a}</p>)}<h4>继续调查建议</h4><p>{s.result.recommendation}</p>{s.result.verdict&&<p>复核态度：{s.result.verdict==='agree'?'同意主要判断':s.result.verdict==='disagree'?'不同意，保留分歧':'认为证据不足'}</p>}<p>限制：{s.result.limitations.join('；')}</p></details></>:<p className="subtle">{s.error||'正在取证，还没有完整结论。'}</p>}<details><summary>实际工具参数、原始返回与引用</summary><pre>{JSON.stringify(s.toolRuns,null,2)}</pre></details></section>):<p className="subtle">尚未运行本次双 Agent 调查。下方旧调查仅供历史参考。</p>}</div>
    <details><summary>数据来源、原始指标与分析边界</summary><p>索引：{c.dataset.collection?.indexHost}；原始采集：{c.dataset.collection?.capturedAt}。采集时核对返回日志与 RPC 收据；仍不能独立证明第三方索引绝无遗漏。</p><p>{run?.online.scope||'本次尚未重新核验公共链样本。'}</p>{run?.online.checkedAt&&<p>在线样本核验：{run.online.checkedAt}；成功 RPC 来源：{run.online.rpcHosts?.join('、')}。</p>}<p>只查询此代币和有界接收方窗口；未做跨协议、全部资产或线下经营调查。两位 Agent 同一模型服务，独立取证不消除共同偏差。数据来自探索性选样，不能据此报告预测准确率。</p><p>研究地址：<a href={'https://etherscan.io/address/'+c.dataset.target} target="_blank" rel="noreferrer">{short(c.dataset.target!)}</a>；锚点交易：<a href={'https://etherscan.io/tx/'+c.anchor.txHash} target="_blank" rel="noreferrer">在区块浏览器核对</a>；截止区块 {c.dataset.toBlock}。</p><pre>{JSON.stringify({dataset:c.dataset,anchor:c.anchor,metrics:c.metrics,online:run?.online},null,2)}</pre></details>
    {c.previousInvestigation&&<details><summary>此前保存的单 Agent 调查（非本次双 Agent 结果）</summary><p>{c.previousInvestigation.headline}</p><p className="subtle">{c.previousInvestigation.generatedAt} · {c.previousInvestigation.toolCalls} 次工具调用。该旧稿不作为本次复核员的证据。</p></details>}</section></>;
}
export function ResearchPanel(){
  const [open,setOpen]=useState(false),[tab,setTab]=useState<'public'|'comparison'>('public'),[data,setData]=useState<ResearchOverview>(),[selected,setSelected]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');const lock=useRef(false);
  useEffect(()=>{if(!open)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;const refresh=async()=>{try{const overview=await researchApi<ResearchOverview>();if(!stopped){setData(overview);setError('');}}catch(e){if(!stopped)setError((e as Error).message);}if(!stopped)timer=setTimeout(refresh,5000);};void refresh();return()=>{stopped=true;clearTimeout(timer);};},[open]);
  const c=data?.cases.find(c=>c.id===selected)||data?.cases[0],busy=data?.cases.some(c=>c.run&&['investigating','reviewing'].includes(c.run.status));
  async function run(){if(!c||lock.current)return;lock.current=true;setPending(true);setError('');try{await researchApi<ResearchRun>('/investigations',{datasetId:c.id});setData(await researchApi<ResearchOverview>());}catch(e){setError((e as Error).message);}finally{lock.current=false;setPending(false);}}
  return <section className="card research-workbench" data-testid="research-workbench"><div className="section-title"><div><span className="eyebrow">研究案例 · 与会员账单分开</span><h2>用公开链证据检验调查能力</h2></div><button className="secondary" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'收起案例':'查看案例与对照'}</button></div><p className="subtle">真实主网历史案例用于检验取证；三个明确标注的模拟样例用于解释“为什么不能只看阈值”。</p>
  {open&&<><div className="research-tabs" role="group" aria-label="研究案例类型"><button className={'secondary '+(tab==='public'?'chosen':'')} aria-pressed={tab==='public'} onClick={()=>setTab('public')}>公开以太坊案例</button><button className={'secondary '+(tab==='comparison'?'chosen':'')} aria-pressed={tab==='comparison'} onClick={()=>setTab('comparison')}>三种方法对照</button></div>{error&&<p className="warning" role="alert">{error}</p>}{data?.error&&<p className="warning">{data.error}</p>}{!data&&!error&&<p className="subtle">正在读取案例…</p>}
  {tab==='public'&&data&&<>{!data.cases.length?<p className="empty">尚未导入可核查的主网案例，不显示虚构结果。</p>:<><div className="research-tabs" role="group" aria-label="选择公开案例">{data.cases.map(item=><button className={'secondary '+(c?.id===item.id?'chosen':'')} aria-pressed={c?.id===item.id} key={item.id} onClick={()=>setSelected(item.id)}>{item.name}</button>)}</div>{c&&<PublicCase c={c} pending={pending} disabled={!data.modelConfigured||!!busy} onRun={()=>void run()}/>}</>}</>}
  {tab==='comparison'&&data&&<div data-testid="comparison-cases"><p className="public-case-notice">模拟方法样例 · 不是链上交易，不是 Agent 已执行的结果，也不是预测准确率测试。</p><div className="comparison-grid">{data.comparisons.map(item=><article className="agent" key={item.id}><span className="plain-status">模拟样例</span><h3>{item.title}</h3><p>收款 {item.metrics.receipts} GYM · 转出 {item.metrics.outflows} GYM · 比例 {percentBps(item.metrics.outflowToReceiptBps)}</p><h4>规则看到了什么</h4><p>{item.ruleResult}</p><h4>Agent 应进一步调查什么</h4><p>{item.investigationQuestion}</p><h4>不能忽略的正常解释</h4><p>{item.normalExplanation}</p><h4>仍然不知道什么</h4><p>{item.unknowns}</p><p className="comparison-outcome">期望表达：{item.expected}</p><details><summary>重算指标与规则信号</summary><pre>{JSON.stringify(item.metrics,null,2)}</pre></details></article>)}</div></div>}</>}
  </section>;
}
